### ISSUE TITLE
Cant see other player while doing online 2 player coop on one pc (ryjiux)

### ISSUE THREAD

**Issue by Dhruv20114341** [fruityloops1/bf-multiplayer#6]
So player 1 is luigi and player 2 is toad, when toad joins only luigi can see him then after i kill luigi then respawn, toad can see luigi now but luigi cant see toad, so only one player can see each other at a time on ryjiux

**Comment by fruityloops1** [comment]
Can you show the User IDs of both of the ryujinx users?

**Comment by Dhruv20114341** [comment]
9473ececf27840aa9bd3584381828acf is Luigi and cbb6c9e1521b4cfcb873de876aaa06f2 is Toad 

so it cant be the default, and i am sure to choose different users when launching the game

**Comment by Sebastrion** [comment]
Yeah, same Problem here.
We are both using Ryujinx, and we can't see the other Player... most of the time.
I try to explain, If we both join the Game, we can't see each other, but sometimes if someone dies, we can see each other.
Sometimes Player 1 can only see Player 2.
Sometimes Player 2 can only see Player 1.
And in very rare cases, Player 1 and 2 can see each other.
![ServerLog](https://github.com/user-attachments/assets/7dcda7b1-ec7f-43ac-ac33-710bf52696da)

To prove that we are using different User IDs:
![id1](https://github.com/user-attachments/assets/600c1628-a7ca-4184-8338-ab6f21eb5c86)
![id2](https://github.com/user-attachments/assets/502065fb-98de-469a-9660-e79067d95e10)

**Comment by fruityloops1** [comment]
Fixed in https://github.com/fruityloops1/bf-multiplayer/releases/tag/2
